/* CCFV // HISTÓRIA — leitura pública */
(() => {
"use strict";
const state={all:[],filter:"TODOS"};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase();
const key=v=>{const n=norm(v).replaceAll(" ","_");if(n.includes("CHAMPIONS"))return"CHAMPIONS";if(n.includes("NIGHT"))return"NIGHT_CUP";if(n.includes("BRASILEIR"))return"BRASILEIRAO";if(n.includes("LIBERTADOR"))return"LIBERTADORES";if(n.includes("MUNDO")||n.includes("WORLD"))return"COPA_DO_MUNDO";return n||"OUTRA"};
const trophy=()=>`<svg viewBox="0 0 80 90"><path d="M28 12h24v18c0 16-5 27-12 33-7-6-12-17-12-33V12Z"/><path d="M28 18H12c1 19 8 29 19 34M52 18h16c-1 19-8 29-19 34"/><path d="M40 63v13M22 84h36M29 76h22"/></svg>`;
function render(){const list=$("#history-list");if(!list)return;const rows=state.filter==="TODOS"?state.all:state.all.filter(x=>key(x.competition_code||x.competition_name)===state.filter);$("#history-total").textContent=rows.length;$("#history-players").textContent=new Set(rows.map(x=>x.player_id||x.participant_id||x.player_name)).size;$("#history-competitions").textContent=new Set(rows.map(x=>key(x.competition_code||x.competition_name))).size;if(!rows.length){list.innerHTML='<div class="ccfv-history-empty">NENHUM TÍTULO REGISTRADO NESTE FILTRO.</div>';return}list.innerHTML=rows.map(x=>{const comp=x.competition_name||x.title||"COMPETIÇÃO CCFV";const player=x.player_name||x.participant_name||"CAMPEÃO";const season=x.season||x.season_label||"TEMPORADA";const team=x.team_name||x.club_name||"CCFV";return `<article class="ccfv-history-entry"><div class="ccfv-history-entry__trophy">${trophy()}</div><div><div class="ccfv-history-entry__competition">${esc(comp)}</div><div class="ccfv-history-entry__name">${esc(player)}</div><div class="ccfv-history-entry__meta">${esc(team)} · CAMPEÃO</div></div><div class="ccfv-history-entry__season">TEMPORADA<strong>${esc(season)}</strong></div></article>`}).join("")}
async function client(){if(!window.CCFVAuth?.getClient)throw Error("Cliente CCFV indisponível.");return window.CCFVAuth.getClient()}
async function load(){try{const c=await client();let r=await c.from("ccfv_titles").select("*").order("awarded_at",{ascending:false});if(!r.error){state.all=r.data||[];render();return}r=await c.from("ccfv_champions_public_hall_v2").select("*").order("created_at",{ascending:false});if(r.error)throw r.error;state.all=(r.data||[]).map(x=>({...x,competition_code:"CHAMPIONS",competition_name:"CHAMPIONS LEAGUE",player_name:x.participant_name,season:x.season_label||x.season}));render()}catch(e){console.error("CCFV // HISTORY:",e);$("#history-list").innerHTML='<div class="ccfv-history-empty">ARQUIVO DE TÍTULOS AGUARDANDO A FONTE OFICIAL.</div>'}}
document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");state.filter=b.dataset.filter||"TODOS";render()}));
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",load,{once:true}):load();
})();