/* CCFV // HISTÓRIA — leitura pública */
(() => {
"use strict";
const state={all:[],filter:"TODOS"};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toUpperCase();
const key=v=>{const n=norm(v).replaceAll(" ","_");if(n.includes("CHAMPIONS"))return"CHAMPIONS";if(n.includes("NIGHT"))return"NIGHT_CUP";if(n.includes("BRASILEIR"))return"BRASILEIRAO";if(n.includes("LIBERTADOR"))return"LIBERTADORES";if(n.includes("MUNDO")||n.includes("WORLD"))return"COPA_DO_MUNDO";return n||"OUTRA"};
const trophyPath=(value)=>{const k=key(value);const paths={BRASILEIRAO:"../assets/images/historia/trofeus/brasileirao.png",CHAMPIONS:"../assets/images/historia/trofeus/champions-league.png",NIGHT_CUP:"../assets/images/historia/trofeus/night-cup.png",LIBERTADORES:"../assets/images/historia/trofeus/libertadores.png",COPA_DO_MUNDO:"../assets/images/historia/trofeus/copa-do-mundo.png"};return paths[k]||paths.BRASILEIRAO};
const trophy=(value,alt="Troféu CCFV")=>`<img src="${trophyPath(value)}" alt="${esc(alt)}" loading="lazy" decoding="async">`;
function render(){const list=$("#history-list");if(!list)return;const rows=state.filter==="TODOS"?state.all:state.all.filter(x=>key(x.competition_code||x.competition_name)===state.filter);$("#history-total").textContent=rows.length;$("#history-players").textContent=new Set(rows.map(x=>x.player_id||x.participant_id||x.player_name)).size;$("#history-competitions").textContent=new Set(rows.map(x=>key(x.competition_code||x.competition_name))).size;if(!rows.length){list.innerHTML='<div class="ccfv-history-empty">NENHUM TÍTULO REGISTRADO NESTE FILTRO.</div>';return}list.innerHTML=rows.map(x=>{const comp=x.competition_name||x.title||"COMPETIÇÃO CCFV";const player=x.player_name||x.participant_name||"CAMPEÃO";const season=x.season||x.season_label||"TEMPORADA";const team=x.team_name||x.club_name||"CCFV";return `<article class="ccfv-history-entry"><div class="ccfv-history-entry__trophy">${trophy(x.competition_code||x.competition_name,`Troféu ${comp} CCFV`)}</div><div><div class="ccfv-history-entry__competition">${esc(comp)}</div><div class="ccfv-history-entry__name">${esc(player)}</div><div class="ccfv-history-entry__meta">${esc(team)} · CAMPEÃO</div></div><div class="ccfv-history-entry__season">TEMPORADA<strong>${esc(season)}</strong></div></article>`}).join("")}
async function client(){if(!window.CCFVAuth?.getClient)throw Error("Cliente CCFV indisponível.");return window.CCFVAuth.getClient()}
async function load(){try{const c=await client();let r=await c.from("ccfv_titles").select("*").order("awarded_at",{ascending:false});if(!r.error){state.all=r.data||[];render();return}r=await c.from("ccfv_champions_public_hall_v2").select("*").order("created_at",{ascending:false});if(r.error)throw r.error;state.all=(r.data||[]).map(x=>({...x,competition_code:"CHAMPIONS",competition_name:"CHAMPIONS LEAGUE",player_name:x.participant_name,season:x.season_label||x.season}));render()}catch(e){console.error("CCFV // HISTORY:",e);$("#history-list").innerHTML='<div class="ccfv-history-empty">ARQUIVO DE TÍTULOS AGUARDANDO A FONTE OFICIAL.</div>'}}
document.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");state.filter=b.dataset.filter||"TODOS";render()}));
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",load,{once:true}):load();
})();