
(() => {
  "use strict";
  const MOBILE_MATCHES="ccfv_mobile_matches";
  const MOBILE_RANK="ccfv_mobile_ranking";
  let client=null, players=[];
  const $=s=>document.querySelector(s), num=v=>Number.isFinite(Number(v))?Number(v):0;
  const toast=m=>{const e=$("#admin-toast");if(!e)return;e.textContent=m;e.classList.add("is-visible");setTimeout(()=>e.classList.remove("is-visible"),3200)};
  async function getClient(){if(client)return client;if(!window.CCFVAuth?.getClient)throw new Error("Autenticação indisponível.");client=await window.CCFVAuth.getClient();return client;}
  async function loadPlayers(){const c=await getClient();const {data,error}=await c.from("players").select("id,name,platform").eq("platform","MOBILE").order("name");if(error)throw error;players=data||[];const opts='<option value="">Selecione</option>'+players.map(p=>`<option value="${p.id}">${p.name}</option>`).join("");["#mobile-home-player","#mobile-away-player"].forEach(s=>{const e=$(s);if(e)e.innerHTML=opts});$("#mobile-stat-players").textContent=String(players.length).padStart(2,"0");}
  function populateStages(){const c=$("#mobile-competition")?.value;const e=$("#mobile-stage");if(!e)return;if(c==="BRASILEIRAO_MOBILE"){e.innerHTML=Array.from({length:38},(_,i)=>`<option value="RODADA_${String(i+1).padStart(2,'0')}" data-round="${i+1}">RODADA ${String(i+1).padStart(2,'0')}</option>`).join("")}else{e.innerHTML=['QUARTAS_01','QUARTAS_02','QUARTAS_03','QUARTAS_04','SEMIFINAL_01','SEMIFINAL_02','FINAL'].map((x,i)=>`<option value="${x}" data-round="${i<4?Math.floor(i/4)+1:i<6?1:1}">${x}</option>`).join("")}}
  async function loadData(){const c=await getClient();const {data,error}=await c.rpc("get_ccfv_mobile_matches");if(error)throw error;$("#mobile-stat-matches").textContent=String((data||[]).length).padStart(2,"0");const r=await c.rpc("get_ccfv_mobile_ranking");if(!r.error)$("#mobile-stat-ranking").textContent=String((r.data||[]).length).padStart(2,"0");$("#mobile-admin-list").innerHTML=(data||[]).slice(0,12).map(m=>`<div style="padding:14px 0;border-top:1px solid rgba(255,255,255,.06)"><strong>${m.home_team} ${m.home_score} × ${m.away_score} ${m.away_team}</strong><div class="ccfv-mobile-muted">${m.competition} · ${m.stage||""}</div></div>`).join("")||'<div class="ccfv-mobile-empty">NENHUMA PARTIDA MOBILE.</div>'}
  async function submit(e){e.preventDefault();const c=await getClient(), stage=$("#mobile-stage").selectedOptions[0], competition=$("#mobile-competition").value;const hp=$("#mobile-home-player").value,ap=$("#mobile-away-player").value;if(!hp||!ap||hp===ap){toast("SELECIONE DOIS JOGADORES DIFERENTES.");return}const payload={p_competition:competition,p_stage:stage.value,p_round_number:num(stage.dataset.round)||1,p_home_player_id:hp,p_away_player_id:ap,p_home_team:$("#mobile-home-team").value,p_away_team:$("#mobile-away-team").value,p_home_score:num($("#mobile-home-score").value),p_away_score:num($("#mobile-away-score").value),p_played_at:$("#mobile-played-at").value?new Date($("#mobile-played-at").value).toISOString():new Date().toISOString()};const {error}=await c.rpc("register_ccfv_mobile_match",payload);if(error){toast(error.message);return}toast("RESULTADO MOBILE REGISTRADO.");await loadData();}
  async function init(){if(!$("#section-mobile"))return; populateStages(); $("#mobile-competition")?.addEventListener("change",populateStages); $("#mobile-refresh")?.addEventListener("click",()=>loadData().catch(e=>toast(e.message))); $("#mobile-match-form")?.addEventListener("submit",submit); try{await loadPlayers();await loadData()}catch(e){toast(e.message)}}
  document.addEventListener("DOMContentLoaded",init);
})();
